[build]
buildCommand = "npm install && rm -rf dist && npm run build && cd client && npm install && npm run build"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
